version: '3.7'

services:
  redis:
    image: redis:7
    container_name: redis-stream-poc-redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - default

volumes:
  db_data: {}

networks:
  default:
    driver: bridge
